### ISSUE TITLE
Suggestion: Move Settings item to Tools menu

### ISSUE THREAD

**Issue by adem4ik** [CuteTorrent/CuteTorrent#10]
![image](https://user-images.githubusercontent.com/4707112/28543833-35e133d4-70d2-11e7-9fa8-aec2f2b9ad3a.png)

Currently there is menu 'Settings' with the only one 'Configuration' item. It looks quite strange. So I think 'Settings' menu can be removed and its item can be moved to 'Tools' menu.

Similar logic is used quite often in different applications, i.e. qBittorent & Download Master:
![image](https://user-images.githubusercontent.com/4707112/28543960-a505d21a-70d2-11e7-89cc-f2ce2ffd9e76.png)
![image](https://user-images.githubusercontent.com/4707112/28544080-20c59d40-70d3-11e7-9f00-efffd8e34605.png)

**Comment by Bhaalspawn** [comment]
i'm happy too see there is someone else who is monitoring cutetorrent. Sorry for OT answer

**Comment by adem4ik** [comment]
Hi, well I'm currently working on English and Russian translations, there is a lot of typos and incorrect wordings. If there is gonna be a release with those language fixes I'll start promoting CuteTorrent. May be it will lead to something big like competition with qBittorent at least.

**Comment by Bhaalspawn** [comment]
i hope. qbittorrent is not even the client i'm using now (i use Tixati),but 3.4 is coming and they say it will have lot of new things
i don't mind if cutetorrent is not used by many users. i asked some things here and Ruslan answered. if many users ask for features,develpers can't do everything users want. so it's good if we are not much.

at beginning of july he told me that new version was coming out but maybe he forgot

**Comment by devrus91** [comment]
Спасибо за правки в русском. Поржал с себя. Особенно порадовал "Пердыдущий"
