### ISSUE TITLE
Interactions with windows toolbar

### ISSUE THREAD

**Issue by Bhaalspawn** [CuteTorrent/CuteTorrent#13]
Cutetorrent can't be minimized on the toolbar clicking on the icon. it can only be brought in foreground but not minimized,this is a bug

(not very important but maybe this is what is cusing the problem with toolbar). Give the chance to hide cutetorrent's tray icon.

**Comment by CuteTorrent** [comment]
As for me minimizing is working well 
![ezgif com-resize](https://user-images.githubusercontent.com/29813878/28641470-157d03d4-7258-11e7-9850-c8ac340f9428.gif)
First click to focus on window. Second to minimize

**Comment by devrus91** [comment]
As for me minimizing is working well 
![ezgif com-resize](https://user-images.githubusercontent.com/29813878/28641470-157d03d4-7258-11e7-9850-c8ac340f9428.gif)
First click to focus on window. Second to minimize

**Comment by devrus91** [comment]
Ok. Look's like in old version bug exists. With new update it will be fixed.

**Comment by Bhaalspawn** [comment]
i have windows 7 and not working

**Comment by Bhaalspawn** [comment]
ah ok i didn't read the new message....good to know!
then you can close this one
