### ISSUE TITLE
Поведение окна программы

### ISSUE THREAD

**Issue by sqqqs** [CuteTorrent/CuteTorrent#18]
Когда я кликаю по иконке программы на панели задач, она должна сворачиваться. Она не сворачивается. Это требует срочного исправления.

**Comment by devrus91** [comment]
проверяйте баги прежде чем создавать новый. Такой баг репортили он уже исправлен.

**Comment by sqqqs** [comment]
Не исправлен. Я скачал последнюю версию, баг в наличии.

![cute](https://user-images.githubusercontent.com/6069350/29836668-882079fa-8cfe-11e7-8f63-06e933e8d29a.gif)

**Comment by devrus91** [comment]
Он исправлен в коде. А последняя версия в данный момент в разработке. В последней доступной версии он присутствует.

**Comment by devrus91** [comment]
https://github.com/CuteTorrent/CuteTorrent/issues/13
